#!/bin/bash

set -e
set -x

ROOT=$(realpath $(dirname "$0"))/..
# echo "ROOT from $0 is $ROOT"

if [[ $(git status -s) ]]; then
    echo "There are some uncommitted changes, finish them:"
    git status -s
    exit 1
fi

"$ROOT/lib/build-doc"
ghp-import -np "$ROOT/html_doc/"
