#!/bin/bash
# tagging for release
# - are we on the right branch?
# - have we committed generated .py and .md files?
# - does the tag not exist yet?

set -e
# set -x

ROOT=$(realpath $(dirname "$0"))/..
# echo "ROOT from $0 is $ROOT"

source "$ROOT/lib/version.sh"

DUNE_VERSION="$(grep version "$ROOT/dune-project")"
if [[ "$DUNE_VERSION" != "(version $OCAML_SKLEARN_FULL_VERSION)" ]]; then
    echo "The version in $ROOT/dune-project is wrong $DUNE_VERSION, set it to $OCAML_SKLEARN_FULL_VERSION"
    exit 1
fi

TAG="$OCAML_SKLEARN_FULL_VERSION"
BRANCH="$SKLEARN_BASIC_VERSION"
echo "Attempting to tag version $TAG on branch $BRANCH."

if [[ $(git status -s) ]]; then
    echo "There are some uncommitted changes, finish them:"
    git status -s
    exit 1
fi

UNTRACKED=$(git ls-files --other --directory --exclude-standard)
if [[ "$UNTRACKED" != "" ]]; then
    echo "There are untracked files, do something about it:"
    echo "$UNTRACKED"
    exit 1
fi

# CURRENT_BRANCH="$(git rev-parse --abbrev-ref HEAD)"
# if [[ "$CURRENT_BRANCH" != "$BRANCH" ]]; then
#     echo "Checking out branch $BRANCH"
#     git checkout "$BRANCH"
# fi

if [[ $(git tag -l "$TAG") ]]; then
    echo "Tag $TAG already exists. Maybe bump the version in lib/version.sh?"
    exit 1
fi

INITIAL_BRANCH="$(git rev-parse --abbrev-ref HEAD)"

git checkout master

# Make sure everything builds in master, and generate the generated
# files.
dune build @install @runtest
"$ROOT/lib/build-doc"

git checkout "$BRANCH"

cp "$ROOT/_build/default/lib/"*.{ml,mli} "$ROOT/lib/"
git add "$ROOT"/lib/*.{ml,mli} "$ROOT/sklearn.opam"
git diff-index --quiet HEAD || git commit -m 'add generated files to release branch'

git tag -a "$TAG" -m "Tag release $TAG."

# Come back to where we were.
git checkout "$INITIAL_BRANCH"
