# THe project version on the OCaml side (basically the skdoc version).
OCAML_SKDOC_VERSION=0.3.0

SKLEARN_BASIC_VERSION=0.22
SKLEARN_FULL_VERSION=0.22.2.post1

NUMPY_BASIC_VERSION=1.18
NUMPY_FULL_VERSION=1.18.5

SCIPY_BASIC_VERSION=1.4
SCIPY_FULL_VERSION=1.4.1

OCAML_SKLEARN_FULL_VERSION="sk$SKLEARN_BASIC_VERSION-$OCAML_SKDOC_VERSION"
OCAML_NUMPY_FULL_VERSION="np$NUMPY_BASIC_VERSION-$OCAML_SKDOC_VERSION"
OCAML_SCIPY_FULL_VERSION="sp$SCIPY_BASIC_VERSION-$OCAML_SKDOC_VERSION"

