# THe project version on the OCaml side (basically the skdoc version).
OCAML_SKDOC_VERSION=0.3.1

SKLEARN_BASIC_VERSION=0.23
SKLEARN_FULL_VERSION=0.23.2

NUMPY_BASIC_VERSION=1.19
NUMPY_FULL_VERSION=1.19.4

SCIPY_BASIC_VERSION=1.5
SCIPY_FULL_VERSION=1.5.4

OCAML_SKLEARN_FULL_VERSION="sk$SKLEARN_BASIC_VERSION-$OCAML_SKDOC_VERSION"
OCAML_NUMPY_FULL_VERSION="np$NUMPY_BASIC_VERSION-$OCAML_SKDOC_VERSION"
OCAML_SCIPY_FULL_VERSION="sp$SCIPY_BASIC_VERSION-$OCAML_SKDOC_VERSION"

